# Generated by Django 5.0.6 on 2026-06-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('records_imported', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('integrity_score', models.FloatField(default=100.0)),
                ('grade', models.CharField(default='A', max_length=4)),
                ('actions_taken', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('currency_inferred', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('payer', models.CharField(blank=True, default='', max_length=255)),
                ('participants', models.JSONField(default=list)),
                ('split_type', models.CharField(default='equal', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_settlement', models.BooleanField(default=False)),
                ('raw_row', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.importbatch')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_EXPENSE', 'Duplicate Expense'), ('MISSING_CURRENCY', 'Missing Currency'), ('MISSING_PAYER', 'Missing Payer'), ('INVALID_SPLIT', 'Invalid Split'), ('UNUSUAL_AMOUNT', 'Unusual Amount'), ('FUTURE_DATE', 'Future Date'), ('AMBIGUOUS_DATE', 'Ambiguous Date'), ('SINGLE_PARTICIPANT', 'Single Participant'), ('SETTLEMENT_MIXED', 'Settlement Mixed with Expenses')], max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('description', models.TextField()),
                ('ai_explanation', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='api.expense')),
                ('import_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='api.importbatch')),
            ],
            options={
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_participant', models.CharField(max_length=255)),
                ('to_participant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
